Metzger dynamic inputs
mitre/redhat-enterprise-linux-8-stig-baseline-old pull request #11
Opened 2023-11-07 21:08 UTC by jrmetzger

2023-11-08 16:22 UTC, aaronlippold commented on controls/SV-230372.rb
> +    unless command('cat /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf').stdout.strip.empty?
We always want some test defied - aka a describe block with a message - so that we are always puting the user in a state that will put them in one of the buckets of skip, passed, failed or NA

2023-11-08 16:24 UTC, aaronlippold commented on controls/SV-230372.rb
> +      describe parse_config_file('/etc/sssd/sssd.conf') do
```
 unless file("#{input("sssd_conf_path")}").exist?
    describe "The sssd.conf file was not found at: #{input("sssd_conf_path")}" do
      skip "The sssd.conf file was not found at: #{input("sssd_conf_path")}"
    end
  else
    if virtualization.system.eql?("docker")
      impact 0.0
      describe "Control not applicable within a container" do
        skip "Control not applicable within a container"
      end
    else
      describe ini("#{input("sssd_conf_path")}") do
        its("pam_cert_auth") { should cmp "True" }
      end
    end
  end
```

If the File doesn't exist - warn the user and exit, else 
  if we are a container - mark the test NA, then exit
  else - run the test of what we expect
EOL

2023-11-08 17:12 UTC, jrmetzger commented on controls/SV-230372.rb
> +      describe parse_config_file('/etc/sssd/sssd.conf') do
Same for SV-230274

2023-11-08 17:42 UTC, aaronlippold commented on controls/SV-230274.rb
> +  sssd_conf_path = input('sssd_conf_path')
You don't need to usually assign this to a local instance variable you can just use the input directly - if you need it as a string you can use `"#{input('key')}"` syntax like you would for any ruby variable.

2023-11-08 17:43 UTC, aaronlippold commented on controls/SV-230296.rb
> +      its('PermitRootLogin') { should eq input('permit_root_login') }
I'd use the `cmp` matcher so that 'No' 'no' and 0 will all work.

2023-11-08 17:48 UTC, aaronlippold commented on controls/SV-230334.rb
> +      skip 'The release is higher than 8.2; this control is Not Applicable.'
You may was put the value of the OS release in the message as well. depending on how it prints out to the user. So something like.

```
This control is Not Applicable since the current OS version of: {version}, is above {os_min_version}.

This way we can have os_max_version, os_min_version and then just adjust the inputs as it changes year to year.

2023-11-08 17:49 UTC, aaronlippold commented on controls/SV-230334.rb
> +    fail_interval = input('fail_interval')
again, I don't think we need a local variable here

The only time you need a local variable is when you are in a describe.one or in a nested describe block. 

Basically just default to using inputs directly, and if it starts to fail then define the local var as needed but only if needed.

2023-11-08 17:49 UTC, aaronlippold commented on controls/SV-230335.rb
> +    fail_interval = input('fail_interval')
same as above

2023-11-16 21:35 UTC, aaronlippold requested changes

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230335.rb
>      describe parse_config_file('/etc/security/faillock.conf') do
We should not have a hard coded path - these should always be inputs with default values

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230334.rb
> +    describe pam('/etc/pam.d/password-auth') do
same as above

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230334.rb
> +    describe pam('/etc/pam.d/system-auth') do
same as above

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230356.rb
> +  describe pam('/etc/pam.d/system-auth') do
sane as above

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
hard coded path and perhaps parse_config_file could be more useful ... this makes it a bit more abstracted

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
Maybe, just thinking out loud on this. 

I always question when the command resource is use especially on conf files.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230273.rb
> -    mfa_pkg_list.each do |pkg|
There are multiple packages needed for MFA which is why we made it an array of packages in the shared resources.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230274.rb
> +  if file(input('sssd_conf_path')).exist?
I don't think the virt check should be nested inside the conf path here. If its a container then its NA, then you can move on to the other state.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230329.rb
>          its('daemon.AutomaticLoginEnable') { cmp false }
you are missing a 'should' here `should be_false` may work best

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230372.rb
> +  if file(input('sssd_conf_path')).exist?
The check for virt should be outside the sshd conf I think

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230406.rb
> +  audit_file = auditd.file('/etc/passwd')
Not sure why you are calling the auditd resource here to set the local instance variable for the expected file path

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230408.rb
> +  audit_file = auditd.file('/etc/group')
ahh I see -- you moved that away from the describe block below ... ok ... readability wise 6 of one half dozen of the other.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230548.rb
> +  elsif input('container_host')
You should update your justification a bit more here   so that clarify why this is NA - aka outside the scope of evaluation - if its a container host. It almost seems like you are saying this should be allowed if it is a container host and if so it should pass and have a positive value here - not be NA.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230548.rb
We also forgot a condition here - it says if the returned value is anything but 0 or not returned - aka nil then .... so we should also make sure our test covers the `nil` case.

something like `{ should be_zero }` may make this very easy.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-245540.rb
> +    describe processes(tool['process']) do
What is this tool['process']? is this going to be an input?

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-244546.rb
> +      skip 'Input override use of fapolicyd'
Your skip message needs to explain the 'why' - The organization is using the Fapolicyd service to manage firewall servies, this control is Not Applicable' - it need to be a full on real sentense that makes sense.

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-244545.rb
> +      skip 'Input override use of fapolicyd'
same as before

2023-11-16 21:35 UTC, aaronlippold commented on controls/SV-230553.rb
> +  input('remove_xorg_x11_server_packages').each do |p|
I feel like the standard gnome-desktop-3 is missing here

2023-11-17 03:46 UTC, jrmetzger commented on controls/SV-230356.rb
> +  describe pam('/etc/pam.d/system-auth') do
```suggestion
  describe pam('/etc/pam.d/test') do
```

2023-11-17 21:12 UTC, wdower reviewed
partial review

2023-11-17 21:12 UTC, wdower commented on controls/SV-230229.rb
> +  describe x509_certificate(input('root_ca_file')) do
Checked and apparently UBI8 doesn't have the default file in existence, so the test skips because it can't find the file. If the file doesn't exist, this test should fail (since you definitely don't have the certs configured right if the expected certs file doesn't exist).

We should refactor to add a check that the file exists.

2023-11-17 21:12 UTC, wdower commented on controls/SV-230230.rb
If I set the `private_key_files` input to see what happens, this one fails on UBI8 because `ssh-keygen` isn't installed. This is one of those lovely situations where the STIG req is still applicable to a container but the actual check text wouldn't work on a default container.

Should a container even be working with private keys? Should this one just be skipped on containers?

2023-11-20 15:33 UTC, jrmetzger commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
@aaronlippold sysctl library resource? Happens a lot in the controls

2023-11-20 15:34 UTC, jrmetzger commented on controls/SV-245540.rb
> +    describe processes(tool['process']) do
https://github.com/mitre/redhat-enterprise-linux-8-stig-baseline/blob/metzger_dynamic_inputs/inspec.yml#L314-L319

2023-11-20 15:39 UTC, jrmetzger commented on controls/SV-230553.rb
> +  input('remove_xorg_x11_server_packages').each do |p|
Not part of the description

2023-11-20 18:31 UTC, aaronlippold approved these changes

2023-11-20 18:32 UTC, aaronlippold commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
No problem - we can review as part of the r12 final review

2023-11-20 18:36 UTC, aaronlippold commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
perhaps but that would really just be a wrapper around parse_config_file? or are you thinking something on the active testing side.

2023-11-20 18:37 UTC, aaronlippold commented on controls/SV-230553.rb
> +  input('remove_xorg_x11_server_packages').each do |p|
Another item to open as an issue for the v12 final review and update

2023-11-20 20:14 UTC, em-c-rod commented on .github/workflows/verify-ec2.yml
> +    runs-on: ubuntu-22.04
Can we put this back to latest? @aaronlippold

2023-11-20 20:16 UTC, em-c-rod commented on README.md
> +#### The following inputs may be configured in an inputs ".yml" file for the profile to run correctly for your specific environment.
@ejaronne Can you review this section of the README?

2023-11-20 20:17 UTC, em-c-rod commented on TODO.md
> +Go through Not Reviewed and Make not applicable against hardened
Should delete this file and put in the PR description or new issues depending on where they are to be addressed

2023-11-20 20:24 UTC, em-c-rod commented on controls/SV-230230.rb
> +      skip 'Control not applicable within a container'
I didn't know this was not applicable within a container. Should we add a more specific message? @aaronlippold

2023-11-20 20:27 UTC, em-c-rod commented on controls/SV-230247.rb
> +    its('group') { should be_in input('var_log_messages_group') }
Is it realistic that there would be more groups than root for the var log messages? Just curious.

2023-11-20 20:28 UTC, em-c-rod commented on controls/SV-230266.rb
>      describe command('grep -r ^kernel.kexec_load_disabled /etc/sysctl.conf /etc/sysctl.d/*.conf') do
Not sure if it's been done already, but I suggest creating new issues in the repo for things that can or should be addressed outside of this PR.

2023-11-20 20:35 UTC, em-c-rod commented on controls/SV-230266.rb
> +      its('stdout') { should match /kernel.kexec_load_disabled(\s+)=(\s+)1$/ }
I think this needs to change to allow for the possibility of no spaces before or after the "=".

According to regex.
\s
 matches any whitespace character (equivalent to [\r\n\t\f\v ])
+ matches the previous token between **one and unlimited times**, as many times as possible, giving back as needed (greedy)

2023-11-20 20:38 UTC, em-c-rod commented on controls/SV-230273.rb
> -    mfa_pkg_list.each do |pkg|
I'm fine with changing it as done in this control if it was otherwise just hardcoded as a single value in an array.

2023-11-20 20:52 UTC, em-c-rod commented on controls/SV-230275.rb
> +  elsif input('smart_card_status')
Maybe I'm reading this wrong..
It seems that if smart status is enabled, the impact is 0.0? 
It feels backwards. What am I missing?

2023-11-20 20:53 UTC, em-c-rod commented on controls/SV-230230.rb
> +      skip 'Control not applicable within a container'
Perhaps can look at `controls/SV-230296.rb` for an example.

2023-11-20 21:08 UTC, em-c-rod commented on controls/SV-230296.rb
> +      its('PermitRootLogin') { should cmp input('permit_root_login') }
@aaronlippold My following comment is outside the scope of Jon's PR, but when I read this control, it looks like the checks could be - the setting is no, it is not yes, and it is not missing or commented out. Because it being no is not yes and not commented out, that is sufficient for the checks?

2023-11-20 21:09 UTC, em-c-rod commented on controls/SV-230296.rb
> +      its('PermitRootLogin') { should cmp input('permit_root_login') }
Also, is it realistic to want `permit_root_login` as an input?

2023-11-20 21:11 UTC, em-c-rod commented on controls/SV-230309.rb
> +    impact 0.0
I don't think this should be an impact of 0.0. That would make this control NA, but it should be Not Reviewed because it was not reviewed on purpose to run the test faster (disable_slow_controls = true)

2023-11-20 21:12 UTC, em-c-rod commented on controls/SV-230329.rb
>          its('daemon.AutomaticLoginEnable') { cmp false }
I don't see what you are saying here @aaronlippold

2023-11-20 21:14 UTC, em-c-rod commented on controls/SV-230332.rb
> +  os_version_min = input('os_versions')['min']
I haven't seen this input pattern elsewhere. Personally, it may be more consistent (for ease of syntax consistency and knowledge) to have two inputs - one that is `os_version_min` and one that is `os_version_max` rather than an array of two things.

2023-11-20 21:15 UTC, em-c-rod commented on controls/SV-230332.rb
> +    describe pam(pam_auth_files['password-auth']) do
Should this be a loop? Or should pam_auth_files be singular? I'm not clear on this.

2023-11-20 21:25 UTC, em-c-rod commented on controls/SV-230337.rb
> +      skip "The release is lower than #{os_version_max}; Currently on release #{os.release}, this control is Not Applicable."
Personal opinion - currently is irrelevant in time when written down... because the reader is reading it at whatever time is currently for them, not the time of run. In written documentation, I try to avoid this word and similar (now, right now, etc.) 
It's fine, but you could delete that word to be more more direct:

`The release is #{os.release}, which is lower than the maximum allowed release of: #{os_version_max}. This control is Not Applicable.`

Also, do we know that all of the os_version_max referenced throughout the controls would be the same?

2023-11-20 21:29 UTC, em-c-rod commented on controls/SV-230368.rb
> +  %w(
I think this is fine. In RHEL7, we updated to have two describe blocks. Not sure if the output would be different / meaningful to choose one way or the other. @wdower 

https://github.com/mitre/redhat-enterprise-linux-7-stig-baseline/blob/8a411f8a76a92edca85ec83e6d2505869301dd69/controls/SV-204422.rb#L38

2023-11-20 21:32 UTC, em-c-rod commented on controls/SV-230500.rb
> +    # describe "Firewalld is not running. Manually validate  Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA). Verify the services allowed by the firewall matc
Is this control still being worked?

2023-11-20 21:33 UTC, em-c-rod commented on controls/SV-230523.rb
> +    describe 'Input override use of fapolicyd' do
Not sure what it should be, but I would suggest more specific, sentence-like info here

2023-11-20 21:36 UTC, em-c-rod commented on controls/SV-244545.rb
> +    describe 'The organization is using the Fapolicyd service to manage firewall servies, this control is Not Applicable' do
Do you mean this to be `not using the fapolicyd service`? It looks like the if statement checks that we are not using it.

2023-11-20 21:41 UTC, aaronlippold commented on .github/workflows/verify-ec2.yml
> +    runs-on: ubuntu-22.04
Sure

2023-11-21 14:13 UTC, em-c-rod commented on controls/SV-230266.rb
> +      its('stdout') { should match /kernel.kexec_load_disabled(\s+)=(\s+)1$/ }
Should it be `(\s+)?[=](\s+)?`

2023-11-21 15:48 UTC, aaronlippold commented on TODO.md
> +Go through Not Reviewed and Make not applicable against hardened
Agreed. Please put TODO in as `#TODO: ....` in the controls and then its easy to click on them in VSCODE to make an issue which we can track.

2023-11-21 16:30 UTC, aaronlippold commented on controls/SV-230230.rb
> +      skip 'Control not applicable within a container'
This really requires a resource to collect all the .pem files on the system and verify they all have passwords. ( open issue for next release )

As for the container question, I could have keys in the container, in a volume attached to the container, etc. 

Is this control documented in the NA spreadsheet for UBI? If so we can leave it an enhance the message for clarity but I think this is one we have to revisit. 

If we have an open issue to revisit on next update/release I am happy to let it go for now.

@wdower @ejaronne

2023-11-21 16:32 UTC, aaronlippold commented on controls/SV-230247.rb
> +    its('group') { should be_in input('var_log_messages_group') }
Yes, we could have an 'admin' group or a set of folks that have access to the syslog server. 

In reality - no one should ever be doing work as 'root' as it masks who they are.

IMO - it should be a finding if the only group is 'root' given I could not tie back changes to those files to a person.

2023-11-21 16:33 UTC, aaronlippold commented on controls/SV-230266.rb
> +      its('stdout') { should match /kernel.kexec_load_disabled(\s+)=(\s+)1$/ }
@jrmetzger does that addition work on your test bed?

2023-11-21 16:38 UTC, aaronlippold commented on controls/SV-230275.rb
> +  elsif input('smart_card_status')
Yes, we should update the input name to either `disable_smart_card' or 'use_smart_cards`. `smart_card_status` is currently a string:
```
  # SV-230273, SV-230275, SV-230351, SV-230376
  - name: smart_card_status
    description: Smart card status (enabled or disabled)
    type: String
    value: 'enabled'
    ```
It should be updated to a boolean and the logic adjusted accordingly.

2023-11-21 16:43 UTC, aaronlippold commented on controls/SV-230296.rb
> +      its('PermitRootLogin') { should cmp input('permit_root_login') }
So we need to add another state here:
```
if in container and we didn't install ssh
  NA
elsif input - allow-root-login-manual-override-by-input
  message: root login is being allowed by input 'x'
  test permit root login yes is ok
 else
   permit root login should not be commented out
   permit root login should be set to no
   end
   ```

2023-11-21 16:45 UTC, aaronlippold commented on controls/SV-230296.rb
> +      its('PermitRootLogin') { should cmp input('permit_root_login') }
I think the intention the concept of what I outlined above but should really be broken into two parts - the test expectation and allowed values are known and we should not override those with exception logic.

2023-11-21 16:46 UTC, aaronlippold commented on controls/SV-230309.rb
> +    impact 0.0
Agreed - generally aka 99/100 disabled controls should be NR not NA.

2023-11-21 16:49 UTC, georgedias commented on inspec.yml
> +    value: 0
The new STIG states that this value should be "1" by default. 
See PR #19

2023-11-21 16:52 UTC, aaronlippold commented on controls/SV-230329.rb
>          its('daemon.AutomaticLoginEnable') { cmp false }
There is no need for the extra if / else here - the requirement is that the setting be explicitly set to 'false' and the control will fail if it cannot find the file. Testing if its there is unneeded. 

If you want to add a protection to the file being missing them it would be an 

```ruby
input(conf_file_path)
if container
  NA
 else
   unless file exists
     the setting should be 'false;
    else
      skip "The file {file} was not found - please ensure your GDM is configured correctly"
    end
  end
   ```

2023-11-21 16:56 UTC, aaronlippold commented on controls/SV-230332.rb
> +  os_version_min = input('os_versions')['min']
```ruby
if platform.version >= 8.3 
  NA
  else
  ...
  ```
  
  No real need for inputs here

2023-11-21 16:58 UTC, aaronlippold commented on controls/SV-230333.rb
Note: This check applies to RHEL versions 8.2 or newer, if the system is
RHEL version 8.0 or 8.1, this check is not applicable. 

Same as above

2023-11-21 17:03 UTC, aaronlippold commented on controls/SV-230333.rb
ahh - I see what you are doing - ok so this is something we can take or leave - but I also see value as we move this control from STIG to STIG - so if for example RHEL9 has this requirement starting in 9.3 vs RHEL8's 8.2 ... this input is helpful for test transfer - what to call the input so it is easy to understand given min version for one requirement vs another may be different.

Given that we would be introducing a whole naming and 'system' for a couple of floats this may be one of those times were we just hard code the values so avoid possible conflict and keep things simple. 

Generally though I like the thinking but this may be a 1/100 were we just use the direct approach.

2023-11-21 17:04 UTC, aaronlippold commented on controls/SV-230335.rb
Review all the controls that use the 'min'

2023-11-21 17:09 UTC, aaronlippold commented on inspec.yml
>  inputs:
This is a bit unclear - with respect to what - and which requirement - as pervasively commented - this may not really need to be an input.

2023-11-21 17:12 UTC, aaronlippold commented on controls/SV-230332.rb
> +  os_version_min = input('os_versions')['min']
We do this inside the resources as these version are stable and wont change given the change already happened in the past.

2023-11-21 17:13 UTC, aaronlippold commented on controls/SV-230337.rb
> +      skip "The release is lower than #{os_version_max}; Currently on release #{os.release}, this control is Not Applicable."
Once we resolve how we want to handle this class of requirements in the profile this will be taken care of.

2023-11-21 17:14 UTC, aaronlippold commented on controls/SV-230500.rb
> +    # describe "Firewalld is not running. Manually validate  Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA). Verify the services allowed by the firewall matc
Looks like we need to add tests here?

2023-11-21 19:03 UTC, jrmetzger commented on .github/workflows/verify-ec2.yml
> +    runs-on: ubuntu-22.04
```suggestion
    runs-on: ubuntu-latest
```

2023-11-21 19:05 UTC, em-c-rod commented on TODO.md
> +Go through Not Reviewed and Make not applicable against hardened
I prefer new issues than in the controls.

2023-11-21 19:05 UTC, jrmetzger commented on TODO.md
> +Go through Not Reviewed and Make not applicable against hardened
Added issue

2023-11-21 19:06 UTC, jrmetzger commented on controls/SV-230247.rb
> +    its('group') { should be_in input('var_log_messages_group') }
yes, for my project HSSEDI, we want the group for /var/log/messages to be owned by root OR splunk. Splunk needs group permissions to read this file. It also requires to open up permissions to g+r

2023-11-21 19:07 UTC, jrmetzger commented on controls/SV-230266.rb
> +      its('stdout') { should match /kernel.kexec_load_disabled(\s+)=(\s+)1$/ }
should work. Will test later, can always make another PR if not. But added

2023-11-21 19:12 UTC, jrmetzger commented on controls/SV-230332.rb
> +  os_version_min = input('os_versions')['min']
@aaronlippold you gave me a task to input these values in case they change. Now you want it hard coded?

2023-11-21 19:13 UTC, jrmetzger commented on controls/SV-230332.rb
> +    describe pam(pam_auth_files['password-auth']) do
pam_auth_files are in a hash of three pam.d files. This accounts for only the system-auth abnd password-auth files (can be a loop of those two). Misses the smartcard-auth file which is also part of the hash

2023-11-21 19:17 UTC, jrmetzger commented on controls/SV-230368.rb
> +  %w(
Same describe on two different files, best to keep it in a loop like previously mentioned (SV-230332)

2023-11-21 19:18 UTC, jrmetzger commented on inspec.yml
> +    value: 0
Good! Our HSSEDI value (release8) is also 1, so originally wanted to override this value

2023-11-21 19:19 UTC, jrmetzger commented on inspec.yml
>  inputs:
huh? You are pointed at the version of the profile

2023-11-21 19:20 UTC, jrmetzger commented on controls/SV-244545.rb
> +    describe 'The organization is using the Fapolicyd service to manage firewall servies, this control is Not Applicable' do
you are correct

2023-11-21 19:21 UTC, jrmetzger commented on controls/SV-230523.rb
> +    describe 'Input override use of fapolicyd' do
used sentence from 244545

2023-11-21 19:42 UTC, jrmetzger commented on controls/SV-230500.rb
> +    # describe "Firewalld is not running. Manually validate  Ports, Protocols, and Services Management Component Local Service Assessment (PPSM CLSA). Verify the services allowed by the firewall matc
Added the test, not sure what the values required, but just added the defaults from my kitchen create

2023-11-22 17:43 UTC, em-c-rod commented on inspec.yml
> +  # SV-230372
Also used in SV-230274.

2023-11-22 17:46 UTC, em-c-rod commented on controls/SV-230274.rb
> +  elsif file(input('sssd_conf_path')).exist?
The STIG text is looking at `/etc/sssd/sssd.conf` and `/etc/sssd/conf.d/*.conf`. In our local testing, our file was in the `/etc/sssd/conf.d/certificate_verification.conf`. With this update, would the user have to change this input in our case? 
If so, is there a way to use this structure but avoid that?

2023-11-22 17:47 UTC, em-c-rod commented on controls/SV-230274.rb
> +    describe parse_config_file(input('sssd_conf_path')) do
Also, this is named path, but it is assumed to be a file..

2023-11-22 17:49 UTC, em-c-rod commented on inspec.yml
> +    value: 'ocsp_dgst=sha1'
Is there a use case for this to be an input? Also, this may hide visibility on spacing issues. For example, we were looking to update this to allow for 0-many spaces before and after the `=` as you have done with some other controls.

2023-11-22 17:55 UTC, em-c-rod commented on controls/SV-230274.rb
> +      its('sssd') { should include('certificate_verification' => input('sssd_certificate_verification')) }
I am not sure if this works with the updated structure you have, but thinking more like this: 
```suggestion
its('sssd.certificate_verification') { should match /ocsp_dgst(\s+)?=(\s+)?sha1/ }
```

2023-11-22 20:30 UTC, jrmetzger commented on inspec.yml
> +    value: 'ocsp_dgst=sha1'
It is using 'sha1' which is definitely old. HSSEDI uses sha256,sha512 (forgot which?). So that value needs to be overwritten. Maybe just keep the ocsp_dgst hard code?

2023-11-23 16:47 UTC, aaronlippold commented
Please do not use waivers - use an `input('skip_...)` to skip the class of tests and add a `desc, 'justification' : ....` with a message like: `The 'nodev` tests .... <reason>, this requirement was Not Reviewed`

2023-11-23 16:48 UTC, aaronlippold commented
Waivers - as it is currently implemented - is really misleading to the evaluator.

2023-11-30 19:14 UTC, aaronlippold commented
we seem to be throwing a Profile Error ...

2023-12-01 21:10 UTC, em-c-rod commented on controls/SV-230222.rb
> +# TODO: should use the linux_updates resource unless this is faster
Can any comments be moved to the describe block? It just makes delta easier in the future. Also, we could make an issue for this on GitHub instead of a TODO in the code which may be better.

2023-12-01 21:17 UTC, em-c-rod commented on controls/SV-230221.rb
> +# al: reviewed
Alternatively, you can click the "Viewed" checkbox in the PR which collapses those controls (the viewed state is saved, meaning if you reload the PR it will still show those as viewed). That also expands controls if changes occurred since you clicked viewed. 

I suggest the "Viewed" button instead of comments so no one has to remove these comments later or show immaterial changes and notifications to the other reviewers and contributors. @aaronlippold

2023-12-05 21:17 UTC, em-c-rod commented on controls/SV-230494.rb
> +    describe kernel_module(input('kernel_modules')['asynchronous_transfer_mode']) do
The updated guidance on this control (and SV-230495, SV-230496, and SV-230497) update the checks from all caps to lowercase. Unless someone knows of a reason to maintain the idea of using all caps, I would pull the latest from main on these controls and delete these four inputs as they wouldn't be necessary anymore.

2023-12-08 12:54 UTC, jrmetzger commented on controls/SV-230494.rb
> +    describe kernel_module(input('kernel_modules')['asynchronous_transfer_mode']) do
Correct, that was the intent. Will update

2024-01-03 02:23 UTC, em-c-rod commented on controls/SV-245540.rb
> +      skip 'We do not want to implement the Endpoint Security for Linux Threat Prevention tool'
```suggestion
      skip 'The organization has chosen not to implement the Endpoint Security for Linux Threat Prevention tool'
```

@aaronlippold Should this be not reviewed and then attested to by the organization instead of impact 0.0 since the STIG says it should have it enabled?

2024-01-04 15:01 UTC, em-c-rod commented on controls/SV-230372.rb
> +        skip "The sssd.conf file was not found at: #{input('sssd_conf_path')}"
@aaronlippold @wdower Should the control be manual review or fail if the file is not found?

2024-01-04 15:30 UTC, wdower commented on controls/SV-230372.rb
> +        skip "The sssd.conf file was not found at: #{input('sssd_conf_path')}"
I would take out this `skip`. If the user gives a wrong file path, the file resource should handle the error.

Otherwise, to be consistent, we'd have to try to catch wrong paths literally every time we read a file, which we don't do.

2024-01-08 15:48 UTC, em-c-rod commented on controls/SV-237643.rb
> +  sudoers_config_files = input('sudoers_config_files').map(&:strip).join(' ')
This provides a profile error when run on a target I have up. (no method `strip` for nil:NilClass).

2024-02-24 16:19 UTC, aaronlippold commented on controls/SV-230545.rb
> +    # Parse the search results into a hash
Let's not forget that we would like to make this a minor resource so we can take all this repeated code and put it in the libraries directory.

2024-02-25 20:03 UTC, wdower commented
Note -- a bunch of these controls give a caveat that reads like "this package should not be installed _unless the ISSO confirms there is a documented need for it for this system_" (see 230558 through 230561 for examples).

In these cases I have added an input that can be used to indicate that the package is required and should not be considered a finding (_gssproxy_required_, _ftp_required_ etc). I have set those up to become MANUAL checks if the user sets those vars to true. I think that you should have to do a full attestation that a package is necessary in order to not have it throw a finding.

We should make a point of telling people how to add an attestation in the README to handle these cases.

2024-03-04 14:43 UTC, em-c-rod commented on inspec.yml
> +  - name: audit_rule_keys
Can this input be deleted in favor of the keyname input that was added? @wdower

2024-03-04 15:04 UTC, em-c-rod commented on inspec.yml
> +  # audit rule for a given file or function
If we don't put this input in the README or inputs.yml file somewhere, can we put a comment here for syntax of using it?

2024-03-04 18:49 UTC, wdower commented on inspec.yml
> +  # audit rule for a given file or function
Done (in the `audit_rules_keynames_overrides` input).

2024-03-04 21:16 UTC, merged