V1r13
mitre/redhat-enterprise-linux-8-stig-baseline-old pull request #45
Opened 2024-03-07 22:22 UTC by wdower

Using delta to update profile to V1R13. There were no updates in the STIG changelog that required an update to the actual InSpec code except for in 230504.

2024-03-07 22:32 UTC, wdower commented
Seems like delta (not sure if it was formatter or the actual delta update) had some issues with the `only_if` blocks. It tried to split them into multiple lines, and then duplicated some of the lines:
```
  only_if('This check applies to RHEL versions 8.2 or newer. If the system is RHEL version 8.0 or 8.1, this check is not applicable.', impact: 0.0) {
    (os.release.to_f) >= 8.2
  }
```
became 
```
  only_if('This check applies to RHEL versions 8.2 or newer. If the system is
  RHEL version 8.0 or 8.1, this check is not applicable.', impact: 0.0) {
  RHEL version 8.0 or 8.1, this check is not applicable.', impact: 0.0) {
    (os.release.to_f) >= 8.2
  }
```

Fixing now.

2024-03-08 14:42 UTC, aaronlippold commented on controls/SV-230263.rb
> +  ref 'DPMS Target Red Hat Enterprise Linux 8'
Let's just remove all these references, they don't really provide any value

2024-03-08 14:46 UTC, em-c-rod commented on controls/SV-251706.rb
> +  tag 'review'
What is `tag 'review'`? @wdower

2024-03-08 14:47 UTC, em-c-rod commented on controls/SV-230263.rb
> +  ref 'DPMS Target Red Hat Enterprise Linux 8'
Done

2024-03-08 14:55 UTC, em-c-rod commented on controls/SV-230221.rb
> +Current End of Extended Update Support for RHEL 8.4 is 31 May 2023.
Looks like these dates are not correct in the logic. Will post an update to this control.

2024-03-08 15:02 UTC, em-c-rod commented on controls/SV-230376.rb
> +     $ sudo grep -ir cache_credentials /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf
Does the logic need to change so that this recursively checks the files in /etc/sssd/conf.d/*.conf? It looks like the only check right now is against the sssd.conf file only 
`sssd_config = parse_config_file('/etc/sssd/sssd.conf')`

2024-03-08 15:08 UTC, em-c-rod commented on controls/SV-244526.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
I'm assuming this was a delta error and this line needs to be put back in? Or should we move the `impact 0.0` within the existing clause below like:

```
if virtualization.system.eql?('docker')
    describe 'In a container Environment' do
        if package('openssh-server').installed?
            impact 0.0
            it . . .
```

2024-03-08 15:09 UTC, em-c-rod commented on controls/SV-244528.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Same comment as SV-244526

2024-03-08 15:10 UTC, em-c-rod commented on controls/SV-244549.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Same comment as SV-244526

2024-03-08 15:14 UTC, em-c-rod commented on controls/SV-251706.rb
> +  tag 'review'
If they were for internal reference, can we remove here and SV-251708?

2024-03-08 15:22 UTC, em-c-rod commented on controls/SV-230372.rb
> +     $ sudo grep -ir cert_auth /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf /etc/pam.d/*
How do we account for the extra path added here?

2024-03-08 15:27 UTC, em-c-rod commented on controls/SV-230493.rb
> +     install uvcvideo /bin/false
Based on my understanding of the kernel_module resource, this change (for all similar controls in this update) should not impact the logic.


https://github.com/inspec/inspec/blob/main/lib/inspec/resources/kernel_module.rb#L59C1-L65C8

2024-03-08 15:41 UTC, em-c-rod commented on controls/SV-244525.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Same comment as SV-244526

2024-03-08 15:45 UTC, em-c-rod commented on controls/SV-251708.rb
> +  tag 'review'
Same as SV-251706

2024-03-08 15:46 UTC, em-c-rod requested changes
Made a few changes like taking out the ref tag, updating README, removing unneeded files, and fixing a control with incorrect dates in the logic. Left questions or comments on other things that may need addressed.

2024-03-08 15:53 UTC, wdower commented on controls/SV-251706.rb
> +  tag 'review'
Both of those had TODO notes in them. Suspect the tag was to mark them as 'needing review.' I have now done that review (the note was to determine if those controls were container-applicable).

2024-03-08 16:21 UTC, wdower commented on controls/SV-244526.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Updated this control to use `only_if` pattern like the rest (which also addresses this comment by replacing the removed logic).

2024-03-08 19:26 UTC, wdower commented on controls/SV-230372.rb
> +     $ sudo grep -ir cert_auth /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf /etc/pam.d/*
Copied a pattern used in the other SSSD checks that does account for multiple paths to the conf file.

2024-03-08 19:26 UTC, wdower commented on controls/SV-230493.rb
> +     install uvcvideo /bin/false
Agreed.

2024-03-08 19:26 UTC, wdower commented on controls/SV-251708.rb
> +  tag 'review'
Removed review tag and the TODO that prompted it.

2024-03-08 19:27 UTC, wdower commented on controls/SV-230376.rb
> +     $ sudo grep -ir cache_credentials /etc/sssd/sssd.conf /etc/sssd/conf.d/*.conf
Changed this control to align with other SSSD controls that do in fact account for multiple sssd config file paths.

2024-03-08 19:29 UTC, wdower commented on controls/SV-244528.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Updated.

2024-03-08 19:29 UTC, wdower commented on controls/SV-244525.rb
> -  impact 0.0 if virtualization.system.eql?('docker') && !package('openssh-server').installed?
Updated.

2024-03-11 18:36 UTC, em-c-rod commented on README.md
> +<<<<<<< HEAD
I know you would catch this, but just as a second set of eyes, you accidentally merged in the merge conflicts. @wdower

2024-03-12 04:59 UTC, wdower commented on README.md
> +<<<<<<< HEAD
Caught. Thanks

2024-03-12 05:00 UTC, merged